---
title: "Cross Validation"
author: "Zeqi Li"
date: "2024-11-12"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(mgcv)
library(p8105.datasets)
library(SemiPar)

set.seed(1)
```

# LIDAR data
```{r}
data("lidar")

lidar_df = lidar |> 
  as_tibble() |> 
  mutate(id = row_number())
```

```{r}
lidar_df |> 
  ggplot(aes(x = range,
             y = logratio)) +
  geom_point()
```
# Cross validation
Compare linear, smooth, and wiggly models

## Training-testing split
```{r}
train_df = sample_frac(lidar_df,
                       size = 0.8)
test_df = anti_join(lidar_df,
                    train_df,
                    by = "id")
```

```{r}
ggplot(train_df, aes(x = range,
                   y = logratio)) +
  geom_point() +
  geom_point(data = test_df,
             color = "red")
```

## Fit three models
```{r}
linear_mod = lm(logratio ~ range,
                data = train_df)

smooth_mod = gam(logratio ~ s(range),
                 data = train_df)

wiggly_mod = gam(logratio ~ s(range, k = 30),
                 sp = 10e-6,
                 data = train_df)
```

Look at fits
```{r}
train_df |> 
  add_predictions(linear_mod) |> 
  ggplot(aes(x = range,
             y = logratio)) +
  geom_point() +
  geom_point(data = test_df,
             color = "red") +
  geom_line(aes(y = pred),
            color = "red")
```
```{r}
train_df |> 
  add_predictions(wiggly_mod) |> 
  ggplot(aes(x = range,
             y = logratio)) +
  geom_point() +
  geom_point(data = test_df,
             color = "red") +
  geom_line(aes(y = pred),
            color = "red")
```
```{r}
train_df |> 
  add_predictions(smooth_mod) |> 
  ggplot(aes(x = range,
             y = logratio)) +
  geom_point() +
  geom_point(data = test_df,
             color = "red") +
  geom_line(aes(y = pred),
            color = "red")
```

## Compare using RMSE
```{r}
rmse(linear_mod, test_df)
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)
```

## Repeat training-testing splits
```{r}
cv_df = 
  crossv_mc(lidar_df, 100) |> 
  mutate(train = map(train, as_tibble),
         test = map(test, as_tibble))
```

```{r}
cv_df |> 
  pull(train) |> 
  nth(2)
```

Fit models and extract RMSEs
```{r}
cv_res_df = cv_df |> 
  mutate(linear_mod = map(train, 
                          \(x) lm(logratio ~ range, 
                                  data = x)),
         smooth_mod = map(train, 
                          \(x) gam(logratio ~ s(range), 
                                   data = x)),
         wiggly_mod = map(train, 
                          \(x) gam(logratio ~ s(range, k = 30), 
                                  sp = 10e-6,
                                  data = x))) |> 
  mutate(rmse_linear = map2_dbl(linear_mod,
                                test,
                                rmse),
         rmse_smooth = map2_dbl(smooth_mod,
                                test,
                                rmse),
         rmse_wiggly = map2_dbl(wiggly_mod,
                                test,
                                rmse))

cv_res_df
```

## RMSE distribution
```{r}
cv_res_df |> 
  select(starts_with("rmse")) |> 
  pivot_longer(everything(),
               names_to = "model",
               values_to = "rmse",
               names_prefix = "rmse_") |> 
  ggplot(aes(x = model,
             y = rmse)) +
  geom_violin()
```

# Nepalese children data
```{r}
child_df = read_csv("data/nepalese_children.csv") |> 
  mutate(weight_ch7 = (weight > 7) * (weight - 7))

child_df
```
```{r}
child_df |> 
  ggplot(aes(x = weight,
             y = armc)) +
  geom_point(alpha = 0.5)
```

## Fit models
```{r}
linear_mod = lm(armc ~ weight, data = child_df)
pwl_mod = lm(armc ~ weight + weight_ch7, data = child_df)
smooth_mod = gam(armc ~ s(weight), data = child_df)
```

```{r}
child_df |> 
  add_predictions(linear_mod) |> 
  ggplot(aes(x = weight,
             y = armc)) +
  geom_point(alpha = 0.5) +
  geom_line(aes(y = pred),
            color = "red")
```

```{r}
child_df |> 
  add_predictions(pwl_mod) |> 
  ggplot(aes(x = weight,
             y = armc)) +
  geom_point(alpha = 0.5) +
  geom_line(aes(y = pred),
            color = "red")
```

```{r}
child_df |> 
  add_predictions(smooth_mod) |> 
  ggplot(aes(x = weight,
             y = armc)) +
  geom_point(alpha = 0.5) +
  geom_line(aes(y = pred),
            color = "red")
```

## Cross validation to select model
```{r}
cv_df = 
  crossv_mc(child_df, 100) |> 
  mutate(train = map(train, as_tibble),
         test = map(test, as_tibble))
```

Apply models and extract RMSE
```{r}
cv_res_df = 
  cv_df |> 
  mutate(linear_mod = map(train,
                          \(x) lm(armc ~ weight, data = x)),
         pwl_mod = map(train,
                       \(x) lm(armc ~ weight + weight_ch7, data = x)),
         smooth_mod = map(train,
                          \(x) gam(armc ~ s(weight), data = x))) |> 
  mutate(rmse_linear = map2_dbl(linear_mod,
                                test, 
                                rmse),
         rmse_pwl = map2_dbl(pwl_mod,
                                test, 
                                rmse),
         rmse_smooth = map2_dbl(smooth_mod,
                                test, 
                                rmse))
```

```{r}
cv_res_df |> 
  select(starts_with("rmse")) |> 
  pivot_longer(everything(),
               names_to = "model",
               values_to = "rmse",
               names_prefix = "rmse_") |> 
  ggplot(aes(x = model,
             y = rmse)) +
  geom_violin()
```

